### ISSUE TITLE
Implement configuratio files system for pypelib

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#103]
One of the capabilities to be supported is tha configuration of the meta variables of django models in the django persistence engine. Moreover this models have to be used by different apps using pypelib, so they have to be not only configurable but they have to support being used by different apps with different app_labels and table names.

**Comment by CarolinaFernandez** [comment]
A possible implementation would be to organize the configuration file through sections, each one for a different application using pyPElib:

> [app_label 1st]
> db_table_RuleModel=
> db_table_RuleTableModel=
> 
> ...
> 
> [app_label Nth]
> db_table_RuleModel=
> db_table_RuleTableModel=

Also: related to #96

**Comment by msune** [comment]
Marking as invalid, this should be solved internally in the pypelib lib as explained here:

https://github.com/fp7-ofelia/pypelib/issues/2
