### ISSUE TITLE
Mail notifications not arriving

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#106]
In principle SMTP server at EICT is properly working. From the shell emails are arriving. Must be something else in the code.

**Comment by CarlosBermudo** [comment]
Solved.
Notifications were sent correctly, but some mail clients treated them as spam.
Waiting for Island Managers confirmations before closing issue.

**Comment by CarolinaFernandez** [comment]
Closing for the release of OCF 0.4.2
