### ISSUE TITLE
mispelling in Flowspace messages

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#110]
FlowSpace Granted:
dpid: 00:10:00:00:00:00:00:05, FS: VALN id: 16, , port number: 12, direction: bidirectional & dpid:

it should be VLAN id and not VALN id

**Comment by CarolinaFernandez** [comment]
Fixed.
- File **optin_manager/src/python/openflow/optin_manager/flowspace/models.py**
  - Changed text from "VALN id" to "VLAN id"
- File **optin_manager/src/python/openflow/optin_manager/opts/models.py**
  - Changed ", port number" to "port number"
