### ISSUE TITLE
Add project name to the flowspace granted mail notification

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#112]
Add project name to the flowspace granted mail notification.
More over, check the flowspace granted shown in the body of the message corresponds with the project/slice and it is not of other slice, or project/slice of the same user.

**Comment by CarolinaFernandez** [comment]
Seems to be the correct flowspace, but waiting for further testing.

### New format for e-mails:

**Island managers: flowspace request**

> [OFELIA CF] Flowspace Request: OptinManager 'project_name'
> 
> Hi, Island Manager
> 
> A new flowspace was requested:
> 
> Project: project_name
> Slice: project_slice
> VLAN range: (x, y)
> 
> You may add a new Rule for this request at: https://<optin_url>/<optin_section>

**User: flowspace request attended**

> [OFELIA CF] Your Flowspace request has been attended
> 
> Your Flowspace request has been attended. You may access your slice page at Expedient's site to check the granted Flowspace.
> 
> Project: project_name
> Slice: project_slice
> Flowspace granted:
> 
> dpid: **:**:**:**:**:**:**:**, FS: VLAN id: x-y, , port number: z, direction: bidirectional
> ...

**User: project membership change**

> [OFELIA CF] Project test membership notification
> 
> You have been added to project 'project_name' as a user with the following roles: 'owner', 'researcher'.
> You may start experimenting now by going to https://<expedient_url>/<slice_detail>/

### Modified files:

> optin_manager/src/python/openflow/optin_manager/admin_manager/helper.py
> optin_manager/src/python/openflow/optin_manager/admin_manager/views.py
> optin_manager/src/python/openflow/optin_manager/opts/views.py
> optin_manager/src/python/openflow/optin_manager/xmlrpc_server/ch_api.py
