### ISSUE TITLE
ofreg: warning in the approval e-mail

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#116]
Might be useful to warn people to log in first to OCF (as a way to definitely activate their account) to be able to participate in other's experiments (so their info is _transferred_ from LDAP), etc.

**Comment by msune** [comment]
Well theoretically speaking there is no need and does not provide any benefit. At the very end users may only use on of the multiple Expedient instances, or even none, and in any case they must request the project (to allow or deny it based on the testbed polices).

**Comment by lbergesio** [comment]
The only benefit that it provides, and the reason why the issue was raised is because a project owner can not add members to the project that have not yet logged in the first time. But not bg deal...

**Comment by msune** [comment]
If this is the case, maybe the right decision is to allow users to request access to a project. That will probably complete the story...

**Comment by CarolinaFernandez** [comment]
That would be easier to implement than allow a user to add another to its project. However, if that solution were going to be adopted I think it should work for both sides.

Q: should not  we check the viability to modify ofreg to synchronize LDAP with our Expedient database on the registration?

**Comment by msune** [comment]
Problem is that you don't know which of the UI instances he/she wants to use, or even multiple... So either you preload on all (which is not necessary and you have to keep track of all the instances) or none (like now).

**Comment by CarolinaFernandez** [comment]
Ok then, let's at least warn the user in the activation e-mail about this requirement. A link to the UI instance would be nice, though not essential.

In the file: `ofreg/registration/views/registration.py` there's a `send_mail` that uses the contents of a .txt file:

**File: `ofreg/registration/templates/mailer/registration_complete.txt`**

> Your registration has been completed.
> Please browse to the login: {{ link }}
> Your login is: {{ login }}
> 
> Please use the password you provided in the registration process.
> 
> Be also aware that in order to ask for a project or to be part of one, you shall log in at least once.
> 
> Best regards
>   Your Ofelia Team
