### ISSUE TITLE
Allow updating the slice controller without having to start/update it

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#121]
By doing this,  the need to request the flowspace again and wait for its approval when the slice is started/updated is avoided.

A new call in the Optin ch_api.py is needed resulting in an changeSlice() call in flowvisor, It is compatible with FV 0.8.1 but for newer version (v1.0 for sure) this is not more compatible since this call was replaced by updateSlice().

**Comment by lbergesio** [comment]
Done.

**Comment by vkotronis** [comment]
Also adapted this to FOAM. Need to check that changing first the flowspace and then the controller for an existing slice does not bypass the admin's approval though

**Comment by vkotronis** [comment]
OK bypassing does not happen since flowspace is deleted from FV upon new reservation. It seems to work fine with FOAM
