### ISSUE TITLE
Warning massage when stoping a slice

### ISSUE THREAD

**Issue by alvico** [fp7-ofelia/ocf#124]
When I stop a slice without Openflow resources it warns  me about that: "it will also delete the granted flowspace" even I have no flowspace

**Comment by CarolinaFernandez** [comment]
This change should be done within the plugin system (`it would be necessary to know 
the set of assumptions under which an alert would be raised on 
start/update/stop slice`), either by:
1. Adding a "slice header template"
2. Using hook methods, either in backend or via JS
3. By adding new settings
4. ...?

A change like that has a number of implications that shall be seen in a close future. As for now, the check is still made in Expedient.

**File: `expedient/src/templates/default/expedient/clearinghouse/slice/detail.html`**

```
function getLoadingMsg(action) {
    var grantedFlowspace = 0;
    if ($("[id^=grantedFlowspace][id$=Container]").length > 0 || 
        $(".grantedFlowspaceHeader").length > 0) {
            grantedFlowspace = 1;
    }
    var flowspaceWarning = 'confirmWrapper("';
    if (action == "start_update") {
        {% if slice.started %}
            if (grantedFlowspace) {
                flowspaceWarning += "Updating";
            }
        {% else %}
            return eval('showLoadingMsg("Loading...");');
        {% endif %}
    } else if (action == "stop") {
        if (grantedFlowspace) {
            flowspaceWarning += "Stopping";
        }
    }
    if (grantedFlowspace) {
        flowspaceWarning += ' the slice will cause all granted 
flowspaces to be deleted in the Flowvisor, and require approval 
for new requests. Are you sure you want to stop the slice?");';
        return eval(flowspaceWarning);
    } else {
        return "";
    }
}
```
