### ISSUE TITLE
Setting loopback interface as slice controller can crash FlowVisor

### ISSUE THREAD

**Issue by vkotronis** [fp7-ofelia/ocf#125]
Setting the controller for a slice to "tcp:127.0.0.1:6633", and then pushing the slice to FlowVior, causes FlowVisor to create numerous connections with itself, affecting all other active slices. In particular, FlowVisor crashes after the number of open connections surpasses a threshold, which can take from 1 minutes to 1 hour, depending on the system performance. During this time, all other slices are also affected. I would propose input sanitization in the controller field. This is a very important problem. It was very difficult to spot the reason for FlowVisor's malfunction in this case, since it just spawns numerous connections that lead to the loopback interface in all slices, effectively DoSing the real controller connections.

**Comment by lbergesio** [comment]
Fix. Controller URL field validator updated to consider this situation. The IP address and domain name  values located in the settings files are neither allowed.
