### ISSUE TITLE
Project description validator is too restrictive

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#126]
The validator of the field Project Description in the form to create a new Project restricts the data to use letters a-z,A-Z, numbers, comma (,) and the hyphen (-) only.
Fix to prevent only written accents.

**Comment by CarolinaFernandez** [comment]
Fixed.

Both project and slices will allow everything but accented characters and some characters local to some countries (e.g. opening question and exclamation marks, ñ, ç, ë, ø)

File: `expedient/src/python/expedient/common/utils/validators.py`

```
DESCRIPTION_FORBIDDEN_RE = ur'[\u00C0-\u017F]+'
def descriptionLightValidator(description):
    # Raise ValidationError if regexp does match (some accents present)
    if re.search(re.compile(DESCRIPTION_FORBIDDEN_RE, re.UNICODE), description):
        raise forms.ValidationError(u"Please do not use accented characters.", "invalid")
```
