### ISSUE TITLE
Python 2.7 (with last django version)

### ISSUE THREAD

**Issue by alvico** [fp7-ofelia/ocf#128]
Prepare the development SDK to use python 2.7 and the last stable version of django for the development of the final OCF version.

**Comment by alvico** [comment]
The debian version should be Wheezy since the Squeeze does not have support for python2.7.

**Comment by CarolinaFernandez** [comment]
Check this out: http://www.debian.org/News/2013/20130504

From this last Saturday, Debian Wheezy is now stable.
Some of the packages we will be interested in are the following:
- Python 2.7.3 and 3.2.3
- Xen Hypervisor 4.1.4
