### ISSUE TITLE
Improve control over the flowspace rules addition

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#13]
When adding a flowspace rule without an assigned experiment [*] conducts to an Internal Server Error page.
This may be improved by raising an alert when the aforementioned conditions are met and the "Add Rule" button is pressed.
- https://<ofeliacf_optin_path:ofeliacf_optin_port>/opts/opt_in

**Comment by msune** [comment]
is this concerning the usual OFELIA workflow with OCF (that means request is made through Expedient UI, and then add rule through Optin UI)?

If it isn't we probably "won't fix" this issue, as we are moving pretty soon to FOAM Openflow AM/RM : https://openflow.stanford.edu/display/FOAM/

**Comment by CarolinaFernandez** [comment]
This behavior happens only through the Opt-In manager interface (Administrate Flowspace > Add Rule).
I will then close this issue and label it as "wontfix".
