### ISSUE TITLE
Expedient and Optin FS mismatch

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#137]
Check today(15-4-13)'s https://llull.ctx.i2cat.net/slice/detail/80/#/

Requested flowspace in expedient:
Flowspace 93    Associated OpenFlow Interfaces
    OpenFlow Switch: 00:10:00:00:00:00:00:04 - Port 12

Requested flowspace in optin:
FlowSpace:
dpid: 00:10:00:00:00:00:00:02, FS: All, direction: bidirectional
dpid: 00:10:00:00:00:00:00:03, FS: All, direction: bidirectional
dpid: 00:10:00:00:00:00:00:04, FS: Allport number: 12, direction: bidirectional
dpid: 00:10:00:00:00:00:00:01, FS: All, direction: bidirectional
VLAN(0,4095)

Granted flowspace in expedient:
Flowspace   Associated OpenFlow Interfaces
VLAN ID: 23 - 23
    OpenFlow Switch: 00:10:00:00:00:00:00:03 -Port 0
OpenFlow Switch: 00:10:00:00:00:00:00:04 -Port 12
OpenFlow Switch: 00:10:00:00:00:00:00:02 -Port 0
OpenFlow Switch: 00:10:00:00:00:00:00:01 -Port 0

In "Book Openflow resources" page there are selected two or three ports per switch .

**Comment by CarolinaFernandez** [comment]
At least the Expedient issue should be checked in the future:
- Requested flowspace is incomplete
- Granted flowspace is not showing the whole set of ports for each switch. Instead, "0" is used (maybe to mean the whole set of ports)

This FS issue may probably be solved in FOAM, anyway...

**Comment by CarolinaFernandez** [comment]
Related to this, but happening only in v0.5 _in a random way_ and lacking some values. 

> [15:57:49] Vassilis Kotronis: no, it had to do with the visualization of the flow space for one AM, sometimes it is not shown as expected (i.e., the values of the fields are missing). Willl try to reproduce it but sometimes a refresh of the page for updating the slice can fix that, not sure why
> [15:58:18] Vassilis Kotronis: so even if the correct flowspace has been granted, it is not shown properly on expedient sometimes only
> [15:58:27] Vassilis Kotronis: it happens with v0.5
> [15:58:27] Carolina Fernández: are you sure that the flowspace was requested from that OF AM?
> [15:58:31] Vassilis Kotronis: not v0.4.3
> [15:58:36] Vassilis Kotronis: yes from the same AM
> [15:59:05] Vassilis Kotronis: so to make it easier maybe it is something on v0.5 changes on the Expedient's side

**Comment by CarolinaFernandez** [comment]
No any other _phantom_ port (usually ports "0") should be added now.
Therefore, no inconsistency (at least from this type) should happen. See #117 for details.
