### ISSUE TITLE
Improve information given by installation/upgrade scripts

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#15]
It would be nice to improve the information provided by the ofver scripts (and the ones called through this file) in further versions.

E.g.: when upgrading from one version (defined in ".currentVersion") to another (defined in "version") and it turns out that both are the same (whether intentionally or because of the lack of it in the sources repository) the script will inform that both are the same, but the user does not know:

"Targeted version and current are the same one. Are you sure you want to force upgrade."
or either
"Cannot upgrade; targeted version is the same as current installed version. Use force if you want to override this..."

It would be better to inform that:

"Targeted version and current are the same one (0.21.1). Are you sure you want to force upgrade."
or either
"Cannot upgrade; targeted version is the same as current installed version (0.21.1). Use force if you want to override this..."

Any other Improvements could be applied anywhere it may be needed for these scripts.

**Comment by msune** [comment]
Agree, we should be moving this issue to pypelib project, since if I am not remembering wrong this script is part of the ofver library.

**Comment by lbergesio** [comment]
true. but you mean ofver repository, not pypelib

**Comment by msune** [comment]
Oh, yes, you are right as usual these days.

thanks

**Comment by CarolinaFernandez** [comment]
That extra information was added for version 0.3.
Closing it, but it would be good to take this into account for future modifications :)
