### ISSUE TITLE
Creating a Experimenter VM 

### ISSUE THREAD

**Issue by adrianols** [fp7-ofelia/ocf#166]
Hi Everyone,

I'm creating a experimenter vm machine  but it does not work.

The error log of of oxa (/opt/ofelia/oxa/log/error.log) is:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/opt/ofelia/oxa/repository/vt_manager/src/python/agent/utils/ServiceThread.py", line 27, in run
    self.__method(self.__param)
  File "/opt/ofelia/oxa/repository/vt_manager/src/python/agent/provisioning/ProvisioningDispatcher.py", line 70, in processProvisioning
    raise e
error: [Errno 110] Connection timed out

Thanks in advance!

Regards,
Adriano

**Comment by msune** [comment]
This exception is thrown by the agent likely due to the fact that the OXA (agent) cannot contact back the VM Manager. The OXA contacts asynchronously the VM Manager, not synchronously, so this means:
- The OXA should be able to reach VM manager; firewalls and appropriate routing is needed. Check specially firewalling between the OXA -> VM Manager.
- VM Manager has as wrong setting in the settings file, leaving the callback URL unusable by OXA (unlikely but possible).

You can enable a higher debug level in `/opt/ofelia/oxa/bin/mySettings.py` of OXA, this should give you more information on the error hopefully, in particular the callback URL. Paste the extended log if you are unable to find the root cause.

Best

**Comment by adrianols** [comment]
Thanks, Marc.

It was in fact a misconfiguration in VM Manager mysettings. The field
VTAM_IP was incorrect.

Now, when I try to start/delete a vm it appears the following message :

NameError: global name 'XMLRPC_USER' is not defined
Error: Device 0 (vif) could not be connected. Hotplug scripts not working.
libvir: Xen error : Domain not found: xenUnifiedDomainLookupByUUID
03/07/2013 03:09:56 PM [Thread-8>XenProvisioningDispatcher.py:103] ERROR:
Could not start VM

I've founded this thread (https://github.com/fp7-ofelia/ocf/issues/162) of
Caroline  but i did not manage to solve it.

Thanks in advance, again!

Best,
Adriano

2013/7/2 Marc Suñé notifications@github.com

**Comment by lbergesio** [comment]
Dear Adriano,

please check that you need to thedine XMLRCP_USER and XMLRPC_PASSWORD in
the mySettings file of the VM Manager and put thesse values too in the
mySettings file of the different instances of the Agent running in the Xen
Servers.

Regarding the interface error most probably you have no configure the
server in your VM Manager properly. Check the interfaces configuration
using the names of the BRIDGES in the server interconnecting the physical
interfaces with the VMs inter
faces.

Best,
Leonardo

2013/7/3 adrianols notifications@github.com

> Thanks, Marc.
> 
> It was in fact a misconfiguration in VM Manager mysettings. The field
> VTAM_IP was incorrect.
> 
> Now, when I try to start/delete a vm it appears the following message :
> 
> NameError: global name 'XMLRPC_USER' is not defined
> Error: Device 0 (vif) could not be connected. Hotplug scripts not working.
> libvir: Xen error : Domain not found: xenUnifiedDomainLookupByUUID
> 03/07/2013 03:09:56 PM [Thread-8>XenProvisioningDispatcher.py:103] ERROR:
> Could not start VM
> 
> I've founded this thread (https://github.com/fp7-ofelia/ocf/issues/162)
> of
> Caroline but i did not manage to solve it.
> 
> Thanks in advance, again!
> 
> Best,
> Adriano
> 
> 2013/7/2 Marc Suñé notifications@github.com
> 
> > This exception is thrown by the agent likely due to the fact that the
> > OXA
> > (agent) cannot contact back the VM Manager. The OXA contact
> > asynchronously
> > the VM Manager, not synchronously, so that means:
> > - The OXA should be able to reach VM manager; firewalls and
> >   appropriate routing is needed. Check specially firewalling between the
> >   OXA
> >   -> VM Manager.
> > - VM Manager has as wrong setting in the settings file, leaving the
> >   callback URL unusable by OXA (unlikely but possible).
> > 
> > You can enable a higher debug level in
> > /opt/ofelia/oxa/bin/mySettings.pyof OXA, this should give you more
> > information on the error hopefully, in
> > particular the callback URL. Paste the extended log if you are unable to
> > find the root cause.
> > 
> > Best
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/fp7-ofelia/ocf/issues/166#issuecomment-20383625>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fp7-ofelia/ocf/issues/166#issuecomment-20440550
> .

## 

Leonardo Bergesio
Distributed Applications and Networks Area - DANA
i2CAT Foundation - www.i2cat.net
C/ Gran Capità 2-4, office 109, Nexus I building
08034 Barcelona, Catalonia (Spain)
T: +34 93 567 9926
F: +34 93 553 2520
W: http://dana.i2cat.net
