### ISSUE TITLE
Call to OXAD breaking alternative (sync) protocol

### ISSUE THREAD

**Issue by SergioVidiella** [fp7-ofelia/ocf#174]
The synchronous call is not working properly, it ends before it should, due to asynchronism of the agent.

**Comment by msune** [comment]
Quick question, why is there a need for OXA to have a synchronous API? Isn't it sufficient that VM AM is blocking until the call has succeeded or timed-out?

**Comment by SergioVidiella** [comment]
In fact that's what it's done in the vt am sync api. Sorry if the title of the issue was confusing, OXA hasn't any sync api.
