### ISSUE TITLE
ofreg URL

### ISSUE THREAD

**Issue by bpuype** [fp7-ofelia/ocf#19]
OFELIA regsitration URL has changed from fuzzy.eict.fp7-ofelia.eu to

https://register.fp7-ofelia.eu

This URL is currently referenced in /ofelia/expedient/src/python/expedient/clearinghouse/settings.py , possibly others. Used for redirecting when users want to reset their password. 

The URL in the source code should be changed as fuzzy will be going offline eventually.

**Comment by lbergesio** [comment]
fixed.
