### ISSUE TITLE
Interfaces mismatch in topology view

### ISSUE THREAD

**Issue by gandroulidakis** [fp7-ofelia/ocf#2]
Experimentation interfaces of the VMs connected to the switch appear to have a mismatch. I have a VM connected with 2 interfaces with a switch and the topology view reports that are connected the other way around and not how they are really connected.

**Comment by msune** [comment]
Confirmed. Assigned and scheduled for v0.3

Thank you

**Comment by msune** [comment]
Fixed in 0.3. Information will be correctly displayed after upgrade to 0.3 (so after resources hash cache removal, as in any other upgrade)
