### ISSUE TITLE
Cant remove assigned MAC and IP ranges after delete broken VMs

### ISSUE THREAD

**Issue by cledsons** [fp7-ofelia/ocf#206]
Hi,

After broken VMs deletion i would like to delete IPs and MAC ranges for reorganization.

When I try to delete ranges in https://x.x.x.x:8445/networking/ip4/delete/1/,  it shows me the message:
Error:Cannot delete Ip4Range. Range still contains allocated IPs

Thanks for any help!!

**Comment by CarolinaFernandez** [comment]
Hi Cledson,

the addresses that refer to the VMs manually deleted are not deleted by those scripts, so you should do that manually as well...

Wiki has been updated to cover this. Check step no. 4 at [Stalled VMs in Expedient and/or in VT AM](https://github.com/fp7-ofelia/ocf/wiki/Operational-troubleshooting#wiki-stalled-vms-in-expedient-andor-in-vt-am).

**Comment by cledsons** [comment]
Solved. Many thanks again!
