### ISSUE TITLE
Automatic FlowSpace Approval

### ISSUE THREAD

**Issue by OscarMoya** [fp7-ofelia/ocf#210]
In order to reduce the time required to get a FlowSpace approved, the Automatic FS approval feature is required.
This enhancement must be optional, giving the final choice to the IM to enable this feature or not, and of course informing him/her every time a new (automatic) FS is approved. 
As en extra requirement, a VLAN manager is required in order to always select a free VLAN for inter/intra-island flowspaces.

**Comment by broadbent** [comment]
I believe GENI has some kind of 'engine' which checks a request and can automatically approve it based on a set of limitations. Maybe you could implement something similar? These limits are set by the IM. There could have three end states: allowed, requires approval or denied. Just my 2¢.

**Comment by OscarMoya** [comment]
I did not know the existence of this "engine" and I doubt if its really suitable to our requirements(due to our multi-island distributed approach) or easy to integrate. I started to implement already a VLAN Manager, the simplest approach to process and get the available VLANs. I designed it to be extended  and enhanced in several ways(performance, concurrency, ...). To be honest, I didn't think about add some policies to the VLAN Manager but it is for sure, a good point to take into account.

Thanks for your comments.

**Comment by msune** [comment]
Vasileios was working in a flowspace clashing engine long time ago. I don't know what is/was the status. Leo knows precisely the exact scope of this flowspace clashing engine.

IMHO should be an essential part of the auto-approval, which doesn't preclude clashing flowspaces should not eventually be approved, but would definitely help admins to set easy auto-approval policies and inspect the current flowspace status.

btw, this can easily be implemented via pyPElib ;)

**Comment by lbergesio** [comment]
I agree with everybody, but this vlan mánager has a different scope than what vassileos implemented in ofam. This one is a huge enhancement in what we already had as "the simple mode" to request a flowspace allowing automatically grant flowspaces based on free vlan/s in all the islands affected. Since in practice we only care about vlans, so far, the clashing mechanism may be too much, although together with policy hooks, easily integrable in a second step.
