### ISSUE TITLE
Error during upgrading from OCF 0.6.1 to 0.7

### ISSUE THREAD

**Issue by cledsons** [fp7-ofelia/ocf#219]
Dear all!
I have upgraded our OCF 0.43 to 0.61 facing some issues, already fixed through https://github.com/fp7-ofelia/ocf/issues/77.
Now Im trying upgrade to 0.7 and a new issue issue came to the fore.

The following errors appeared:

 info#  Using default backup module...
/usr/lib/pymodules/python2.6/registration/models.py:4: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha
/usr/lib/python2.6/dist-packages/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
Error: Unable to serialize database: VM matching query does not exist.
WARNING: Could not backup data. Check database for inconsistencies in foreign keys or many-to-many relationships
Trying to dump DB using: mysqldump --databases expedientXXXXXX--user='XXX' --password='xxxxxxx' --host=127.0.0.1 > /opt/ofelia/expedient/bin/rescue/16:17-070414#13053/dbdump.sql
Updating fa90f3f..3272ba7
error: Your local changes to '.gitignore' would be overwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.
FATAL ERROR: Could not upgrade ofver code

Any help?

Thanks!

**Comment by CarolinaFernandez** [comment]
Dear Cledson,

we have spotted the first error, but have not fixed it yet. We'll link the commit with the solution to this issue when that is done.

As for the 2nd error: did you have a modified `.gitignore` file in your OCF root folder? If so, it would be convenient to stash (save your local changes apart -- you would have to recover these changes afterwards) or checkout (discard your local changes) it prior to any operation with ofver.

We will let you know when that issue happens no more. You may wait for it if the upgrade is not crucial for your testbed or either try checking out or stashing and trying again the upgrade.

**Comment by CarolinaFernandez** [comment]
Hi, Cledsons. The error has been fixed and will be incorporated into the next release of OCF (which should be `0.8.1`). We'll keep this open until it is ensured not to happen anymore.
