### ISSUE TITLE
Check: Users certificates are not created in some environments

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#22]
User certs at expedient/src/python/expedient/clearinghouse/gcf-x509-user.crt/ are not created in some environmets (like my SDK or i2CAT preprod).

**Comment by CarolinaFernandez** [comment]
Fixed.

This was due to improper permissions on the gcf-x509-\* folders. These folders and the `pre-upgrade-hook` file for the upgrade to v0.3.1 have now the **exact permissions** as in production.
