### ISSUE TITLE
Improve page scrolling within the topology layour using d3

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#25]
Currently scrolling is done by hidding the island ellipses and using jquery over the #target div. It should be probably done using some d3 feature not needing to hide the ellipses.

**Comment by CarolinaFernandez** [comment]
Fixed by Sergio as of 0.4.

Improved the scrolling, the dragging&zoom and the positioning of the nodes (in concentric circles).

Features added:
- Zoom of clicked area
- Layout handling improvement (charge parameter, etc)
- Automatic grouping of nodes according to its island
