### ISSUE TITLE
[HIGH] Register callback events with libvirt

### ISSUE THREAD

**Issue by OscarMoya** [fp7-ofelia/ocf#27]
Register callback events during the virtual machines lifecycle to improve the communication between agent and VMManager

**Comment by OscarMoya** [comment]
Libvirt Lifecycle events(start and stop) are detected and a callback is sent to VM Manager via xmlrpc communication using a similar structure off 'listVMs".

This callbacks update the states of a vm when is manually started/stopped or when a vm "crashes"(out of control of the users")

These callbacks are interfered with the messages between Expedient<-->VMmanager<-->Agent communications if the action status(Ongoing/success ...)  arrives later than the callback does.

**Comment by CarolinaFernandez** [comment]
Found some issues trying to access the VMs;

when a VM is started through the Expedient it is in fact in "running" state at Xen (`xm list`) and two virtual interfaces are generated at the server where the VM was created. However, it is impossible to access the VM (nor with a ping, neither with SSH).

If the agent code at that server is in the 'development' branch the previous will happen. Using the stable version it works as expected... (Note: ping from pre-production, not the server itself -- wondering why it is not possible to find the VM from there...)
