### ISSUE TITLE
Loop free topology detection

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#37]
Detect loops in requested topologies and warn user.

**Comment by OscarMoya** [comment]
Done.

Loops are detected using a Depth First Search algorithm. A pointer follows the nodes connections and if  this pointer arrives two times to the same node, then there is a loop.

In the file expedient/src/static/expedient/clearinghouse/media/default/js/topology.js there are some tests and detailed comments on how this algorithm works.
