### ISSUE TITLE
Disable VM creation when VM aggregate is down

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#40]
Adding a new virtual machine in one of the slice servers should not be possible when the aggregate manager is down (red cross in "VT aggregate" > "status").

That could be done via Javascript (change the form action to a error URL and raise and alert/message) and/or via Python.

**Comment by msune** [comment]
It is always nice to have a quick alert from the UI side (using JS/AJAX), but it must always be inforced in the backend code. This also and specially applies to the validation of fields (for security reasons, such as deliverately malformed html POST forms).

**Comment by CarolinaFernandez** [comment]
That's right :) I am a supporter of double validation (frontend, then backend), but added the "or" so as to leave the issue handling open to other possibilities.

**Comment by CarolinaFernandez** [comment]
Fixed.

**Check in Javascript**: located at `expedient/src/python/expedient/ui/html/templates/html/plugins/vt.html`. When the AM is down an alert is raised and the flow goes on through the next check.

**Check in Python**: located at `vt_plugin.controller.dispatchers.GUIDispatcher.goto_create_vm`. It asks for the aggregate status. If it is down a DatedMessage (error type) will appear at the top, then redirected to the same page (slice detail).
