### ISSUE TITLE
Cross dependencies between Expedient and VM Manager affecting installation

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#43]
Expedient uses XmlHelper which is imported from the communications module of VM Manager.  This modules id performing local (within the VM Manager) in its **init**.py file which are chained to pypelib. Expedient installation fails when trying to syncdb because pypelib is not installed.

Try to avoid import from **init**'s and study how to isolate Expedient and VM Manager. First solution is sym links in Expedient to VM Manager utilities in order to avoid having duplicated classes.

**Comment by CarolinaFernandez** [comment]
Fixed.

Imports at vt_manager.communication.__init__ moved to vt_manager.urls. This whay the communication package and all its contents may be used independently from other modules.
