### ISSUE TITLE
Ofver cannot be run again when user manually halts it

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#46]
When the OCF installation is manually halted (e.g. because of some bad data in the certificates) it won't remove the .ofverLock. When the user tries to start it again it won't be possible without removing the file first.

It should rather not depend on a file, but on system tools (ps, check process PIDs and folders where these are being executed).

Some other bugs found:
- In the case the ofver script is not run by root the error text --and all the following text-- is set to black, impossible to see in a console with black background
- Some messages pointed to file paths that were incorrect. Example: `/opt/ofelia/expedient//src/python/expedient/clearinghouse/localsettings-example -> /opt/ofelia/expedient//src/python/expedient/clearinghouse/localsettings-example.py` should be `/opt/ofelia/expedient//src/python/expedient/clearinghouse/localsettings-example -> /opt/ofelia/expedient//src/python/expedient/clearinghouse/localsettings.py`

Also, the installation process could be a bit more clear if the headers (main setup steps) were in bold.

**Comment by CarolinaFernandez** [comment]
Fixed.

ofver was upgraded to v0.22 in the Google Code website.

**Comment by lbergesio** [comment]
it is not possible to execute ofver, always finds an instance running and halts

FATAL ERROR: Could not acquire lock... Other instance (PID 7423) of ofver is already running.

**Comment by lbergesio** [comment]
new lock mechanism uses bc, which is not installed by deafult.
fixed avoiding the use of bc and just adding 0 to the pid value in order to be treated as integer.

**Comment by CarolinaFernandez** [comment]
Right, bc does not seem to be installed by default on all Linux distro's.

Change was as follows:

> \-               if [[ `echo ${pids[$i]} | bc` -lt $((currentPID-1)) &&
> +               if [[ ${pids[0]+0} -lt $((CURRENTPID-1)) &&

However this new line does not lock future instances of ofver (as of Ubuntu 11.10): adding that "0" inside { } instead of (( )) does not work as it might be expected but gets the last number added, in this case "0". Therefore the script understands that `pids[$i]` is "0", which will be always less than the current PID, breaking the condition and allowing N instances of ofver.

This line seems to work, yet it must be tested on Debian 6:

> if [[ $((pids[$i]+0)) -lt $((currentPID-1)) &&

**Comment by lbergesio** [comment]
The line worked in Debian 6. Changed, 
This issue will be closed, but a new one not attached to v0.4 milestone will be created to update this in the ofver repository and to considere reimplementing the lock file mechanism.
