### ISSUE TITLE
Intra-Federation issue

### ISSUE THREAD

**Issue by mayur007** [fp7-ofelia/ocf#5]
Different Island OpenFlow-AM selection for flowspace creation reports errors. Moreover the flowspace request message reaches only one islands optin not the other island though resources of both islands are included in the request. 

reproducible at UEssex Island : home ->project Intra_fed -> slice full_fed_ethz

**Comment by msune** [comment]
Thank you, scheduled temporally to v0.3

**Comment by lbergesio** [comment]
several visualization errors fixed. Regarding the orchestration in internal tests it works fine as long as all the dpids of the different switches are different (which must and is the case of OFELIA and its several islands). Access to the machine/s hosting the CF is required for debugging .

**Comment by lbergesio** [comment]
The problem is due to lacking of permission can_use_aggregate of he user depending on the order the users and aggregates are added to the project. Probaby fixed. further testing required

**Comment by msune** [comment]
How should we proceed here to further test the patch?

**Comment by lbergesio** [comment]
Should be now tested in production environment with v0.3 release.
