### ISSUE TITLE
Improve project request's form

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#52]
Improve the form used by the user to ask for a project. It has to be specified (in addition to the tooltip) at least the project name, organization, approx. duration and description.

One option is to include this entries in the same text area. The other one is create a better form but it should be accordingly modifiied the backend to treat the new form.

**Comment by CarolinaFernandez** [comment]
Fixed.

These fields are now required in the ModelForm and concatenated in the backend to create an understandable message for the user who gives the permission / creates the project.
