### ISSUE TITLE
Create VLAN allocation mechanism within FOAM

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#60]
Create a VLAN allocation DB (slicing method) in FOAM. Work can be derived from the work carried on in VM Manager concerning IP/MAC pool allocation.

**Comment by vkotronis** [comment]
This mechanism is already embedded in the flow space clashing checker and I have also maintained the API call that yields the available vlans to expedient. Also, the appropriate calls to handle the VLANs have been added to the admin api.The calls are not accessible over standard CLI yet, but they can be accessed with the curl tool on https://<foam-host>:<port>/core/admin/.
Example:
curl -kn -u foamadmin:$(cat /opt/foam/etc/foampasswd) https://localhost:3626/admin/offer-vlan-tags
In general, curl tool can be used to access any API available in FOAM, over https.
