### ISSUE TITLE
Adapt or create a management GUI for FOAM

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#61]
Adapt or create a management GUI for FOAM. There was some work already done by some folks in the USA concerning an HTML5 UI.

**Comment by vkotronis** [comment]
This is low priority and for the immediate adoption of FOAM we will use its embedded CLI.

**Comment by vkotronis** [comment]
Have learned how to modify the cli at will, so a GUI is obscure. Any partner that wants new functionality can consult me to learn how to modify the internal cli. Potential GUI functionality will be considered after the main OFAM is up and running in coordination with the OCF (Expedient).
