### ISSUE TITLE
Implement a flowspace clashing engine in FOAM 

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#62]
Implement or extend the existing flowspace clashing engine in order to expose non-automatic slice allocation (e.g. VLAN) flowspace conflicts (for instance in optin-like situations)

**Comment by vkotronis** [comment]
The Flow Space clashing engine is now encapsulated within FOAM. More tests pending, but the bulk of the code is there and it works for arbitrary flow spaces (including vlans)
