### ISSUE TITLE
[CRITICAL] AM update 'randomly' fails due to some permissions error

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#73]
When updating an Aggregate Manager there is the possibility that this operation returns an error. This has happened so far in bursts of incorrect updates.

In the file _expedient/src/python/expedient/common/permissions/shortcuts.py_ there is a call to the method

`get_permittee_from_threadlocals(kw)`

that gets local threads (and will later fetch the ones corresponding to the given user kw).

The local threads are obtained from the file  _expedient/src/python/expedient/common/middleware/threadlocals.py_, in the method

`get_thread_locals()`

When the stack of local threads to be returned (`_thread_locals.d_stack`) has >=1 elements it will work as expected. Otherwise the previous 'get' will trigger a failure (due to the bad access to `_thread_locals.d_stack[-1]`) that is shown to the user as an Internal Server Error.

**Comment by lbergesio** [comment]
threadlocals is a kind of "global" variable in django. It is used in Expedient to store any kind of objects in a dictionay that will be available for everyone. It is mostly used to pass permissions owners or users to check their permissions. Difficult to debug because it is a middleware. It is needed to understand its behaviour and most probably replace threadlocals to do this functionality.

**Comment by CarolinaFernandez** [comment]
Fixed.

For the sake of clarifying what was the reason of this bug, the following explanation may be useful in the future.

## Initial assumptions
- [Apache] For every request there is a thread
- [ThreadLocals middleware] Each request or thread needs its own _permission_ (implemented by a list of dictionaries that contains the name of the project, slice and current user). This is obtained by using threading.local() from Python libraries.
- [ThreadLocals middleware] Every time a request is processed, a new permission **pushed** to a list of dictionaries.
- [ThreadLocals middleware] Every time a response is processed, the previous permission is **pop'ed** from the list of dictionaries.
- [Django] The middleware _plugins_ are a set of **ordered hooks** (H1…Hn) that override methods as `process_request` (order: H1…Hn) or `process_response` (order: Hn…H1). When some middleware returns a HttpResponse in the `process_request` method, Django obtains a result and ignores the following. After this, every `process_response` methods are invoked in reverse order (and, in contrast with the request flow, all and every one of these are run -- even when something is returned). [See more](https://docs.djangoproject.com/en/1.2/topics/http/middleware/).

## The problems
1. _Sometimes there was an error when updating an Aggregate Manager._
   
   ThreadLocals were being used to store a stack of the aforementioned permissions for every thread. However, **as stated in [1](https://groups.google.com/d/msg/django-users/5681nX0YPgQ/Jkx-CvNraOsJ), [2](http://www.mail-archive.com/django-developers@googlegroups.com/msg32299.html) and [3](https://groups.google.com/forum/#!msg/django-users/9ZE8PZ6fOZA/cgm-eaYvW-gJ)**, ThreadLocals do not always seem to properly isolate memory for every thread, thus some threads were apparently accessing other's memory. The latter led to desynchronization between the number of inserts (push's) and retrievals (pop's), which returned an **untreated** IndexErrorException when it tried to apply a _pop_ on a stack that was not filled in the request treatment. This exception was sent back to the response processing flow and ultimately to the GUI.
   
   **Note**: the circumstances under which this happened are directly related to the existence of different threads with the same ID in different processes. In fact, this happened no more when Apache's Virtual Host macro `MultiWSGIDaemonProcess` was modified to allow only one thread.
2. _The Internal Server Error (500) that happened when accessing directly to the update page for an AM_ was due to the lack of the final slash.
   
   **URL matching in Django**
   
   > By default, Django tries to match the URLs in the `urls.py` file. [If none was found, the method `process_request` inside `CommonMiddleware` adds a slash and tries to match this _new url_ again.](http://stackoverflow.com/questions/9463173/append-slash-not-working#9472736) If this time a match was finally obtained, an HTTPResponseRedirect is sent; thus the flow to process the request is over and the flow to process the response is started. When this is done, the request with the _new url_ is treated and both processing flows are executed again.
   
   **Middleware processing in Django**
   
   > Middleware classes are processed in the order they appear. The CommonMiddleware class is higher up than the ThreadLocals class, so is processed first. It performs a redirect (with the slash) because the given URL does not end with a slash, so it returns an HttpResponseRedirect. [If a request middleware returns a response, as in this case, no further request middleware classes are processed, so the _push_ cannot be performed. However, response middleware classes are always processed, so the _pop_ is _done_.](http://stackoverflow.com/questions/1795226/django-middware-only-process-response-when-miss-trailing-slash).
   
   As the `process_response` flow starts in reversed order than the processing of the request, the `ThreadLocals`'s middleware is called. The `process_response` invokes a pop() on the 'permission' stack (under the assumption that the request previously crossed the method `process_request` in this very same middleware). This pop() tries to get the last element on the stack, but the stack is empty. An error 500 is raised --instead of the error 404 that Django would expect-- and the next round (with the correct URL, obtained by adding a slash) cannot be done.

## The solutions
1. _Modify the _local thread permission_ structure to make it thread-safe._
   
   Each thread shall access now only the data in the structure identified with a given id (`processID_threadID`).
   
   If for any reason it happened before that a thread X accessed the `_thread_locals.d_stack` of a thread Y now it cannot happen (avoiding the case in which `X._thread_locals.d_stack` was already emptied and a Y tries to _pop_ from it)
2. _Make a proper treatment of the exception raised when a _pop_ cannot be made._
   
   There is no error 500 now, so the Django processing of requests and responses works as expected. Now a user may not use a trailing slash and Django will perform the correct matching, retrieving the correct page in the end.

The file `expedient/src/python/expedient/common/middleware/threadlocals.py` was modified.

## References
1. https://groups.google.com/d/msg/django-users/5681nX0YPgQ/Jkx-CvNraOsJ
   
   > (...) for older Python versions where one may have been using Python implementation of threading locals, ie., the threading_locals module, as in that case data for other threads was exposed, but for latest Python versions believe it is a bit harder to get at thread locals for another thread.
2. http://www.mail-archive.com/django-developers@googlegroups.com/msg32299.html
   
   > Finally, one of the problems of thread locals is that they don't provide strong 
   > isolation between threads (everything is in the same memory space after all).
3. https://groups.google.com/forum/#!msg/django-users/9ZE8PZ6fOZA/cgm-eaYvW-gJ
