### ISSUE TITLE
AMs should be prone to be removed from projects and slices

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#74]
In case there is any conflict between aggregate managers it should be possible to remove the offending aggregate managers from a slice or even from the whole project (and all the slices inside).

**Comment by CarolinaFernandez** [comment]
Done.

The model of the Aggregate has methods to remove itself either from the project or from the slice. Apart from the corresponding changes in the html there is a main change in the aggregate.remove_from_project; that will now also call to aggregate.remove_from_slice from every slice inside the project where the AM is.

**Comment by msune** [comment]
Great, congrats!

Just a minor comment, make sure testing covers all possible changes and check for consistency. 

Some months before I was having a look at that (with very low priority), and if I am not wrong, the AM plugins generate some state that may polute the DB (specially the permissions tables) with outdated information. 

But probably you had checked all this before ;)

**Comment by CarolinaFernandez** [comment]
As for now I can ensure that the requested flowspace for an AM in a slice is kept in the database even when the AM is removed from that slice.

It might be also that these permissions are still kept in the database, but didn't find them yet.

Will keep on with the issue in some time...

**Comment by CarolinaFernandez** [comment]
Also, **VT AMs should not be removed from a slice or project if these contain VMs**.

To do this:

**File `expedient/src/python/vt_plugin/models/VtPlugin.py`**
- In method `remove_from_slice`: check that there is not any VM for the given aggregate inside the slice; then runs parent method.
- In method `remove_from_project`: check that no slice inside the project contains VMs for the given aggregate (it does not run the parent method later). Returns a list of the _offending slices_ and **removes the AM for the rest**.

Appropriate exception handling was coded for slice and project views.
