### ISSUE TITLE
Add e-mail configuration to localsettings.py

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#82]
Add the parameters in the mail configuration file in `expedient/src/python/expedient/clearinghouse/defaultsettings/email.py` to the Expedient's `localsettings-example` file.

Otherwise the Expedient tries to use the Ofelia configuration and thus the e-mail sending will fail.

**Comment by CarolinaFernandez** [comment]
Shall we definitely remove the `email.py` file after we copy these settings?

**Comment by msune** [comment]
All OFELIA installations are using this settings. We should not do it unless we force ofver/IM to fillin this configuration.

I would leave it for the moment.

**Comment by CarolinaFernandez** [comment]
Done.

Email's settings file will be kept then, at least for the moment.
