### ISSUE TITLE
Update/start slice stops unnecessarily VMs

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#86]
Update/start slice stops unnecessarily VMs

**Comment by CarolinaFernandez** [comment]
Both `start` and `update` methods point to `<path_to_url>/slice/start/<slice_id>/`. Therefore:

file `expedient/src/python/expedient/clearinghouse/slice/models.py` has the following code, in which all aggregates are started. If there were any problem starting these, the method will try to stop them back.

**Might be this the unnecessary stopping of VMs you are referring to?** _(line 12)_

> ```
> def start(self, user):
>     (...)
>     for i, agg in aggs:
>         logger.debug("starting slice on agg %s" % agg.name)
>         try:
>             agg.as_leaf_class().start_slice(self)
>             (...)
>         except Exception, e:
>             logger.error("Error starting slice on agg %s" % agg.name)
>             if isinstance(agg.as_leaf_class(),VtPlugin):
>                 try:
>                     agg.as_leaf_class().stop_slice(self)
>                 except Exception, e2:
>                         (...)
>                         DatedMessage.objects.post_message_to_user(
>                         msg_text="Error stopping slice %s on "
>                         "aggregate %s" % (self, agg.name),
>                         user=user, msg_type=DatedMessage.TYPE_ERROR)
>                 exceptions.append(e)
>                 (...)
> ```

This seems to be there to avoid any unstable status if a VM could not be properly started. I guess that if a virtual machine could not start then it's still stopped and then there'd no need of stopping it again; but still it seems like a good idea to stop in case of error. Plus, this should only happen when some exception arise...

**Comment by lbergesio** [comment]
This was decided to b done this way, so that start/stop starts/stops all AM available in the slice, included VMs. I agree it is not the best way. It will be changed to act only on OF AMs.

**Comment by lbergesio** [comment]
Done. Start slice does not start vms but stop slice does stop them.
