### ISSUE TITLE
VM naming conflicts (moved to OCF v.0.3.1)

### ISSUE THREAD

**Issue by vkotronis** [fp7-ofelia/ocf#89]
There is the probability of naming conflicts when VT manager tries to start two VMs with the same name. For example, if two users in different slices choose the same VM server of an island to create two VMs with the exact same name (e.g. "controller"), one of the two VMs will not be able to start when the other one is alreadty running. In fact, there is no exception thrown at the Expedient's level (just the conflicting VM takes forever to start), and the XEN server (oxad) log reports naming collisions and inability to start the VM. Shoudn't the user-defined VM names be sanitized before reaching the agent to avoid conflicts?

p.s. If this is a double-ticket please ignore it.

**Comment by msune** [comment]
How ended this, in theory this was handled by:

```
def __findAliasForDuplicatedVmName(vm):
```

Was the issue invalid?

best
marc

**Comment by vkotronis** [comment]
It seems to be still valid, I have moved it to the OCF v0.3.1 issue set because it is important: when we start attracting more and more experimenters it gets harder and harder to preclude collisions manually. I think that also Mayur had a similar issue, the best would be a resolution with the new OCF version.

**Comment by CarolinaFernandez** [comment]
(See #90)
