### ISSUE TITLE
Incorrect link in activation e-mail

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#91]
The e-mail that is sent after registration is similar  to:

> Activate account at OFELIA CF Clearinghouse:
> https://<production IP>/accounts/activate/<activation token>/
> Link is valid for 3 days.

However, when accessing it, a 500 error is shown:

> [Fri Nov 30 09:57:00 2012] [error] [client 10.216.126.4] mod_wsgi (pid=3654): Exception occurred processing WSGI script '/opt/ofelia/expedient/src/wsgi/expedient/clearinghouse/django.wsgi'.
> [Fri Nov 30 09:57:00 2012] [error] [client 10.216.126.4] Traceback (most recent call last):
> [Fri Nov 30 09:57:00 2012] [error] [client 10.216.126.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 241, in **call**
> [Fri Nov 30 09:57:00 2012] [error] [client 10.216.126.4]     response = self.get_response(request)
> [Fri Nov 30 09:57:00 2012] [error] [client 10.216.126.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 141, in get_response
> [Fri Nov 30 09:57:00 2012] [error] [client 10.216.126.4]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
> [Fri Nov 30 09:57:00 2012] [error] [client 10.216.126.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 100, in get_response
> [Fri Nov 30 09:57:00 2012] [error] [client 10.216.126.4]     response = callback(request, _callback_args, *_callback_kwargs)
> [Fri Nov 30 09:57:00 2012] [error] [client 10.216.126.4] TypeError: 'str' object is not callable

Changing the IP from production's to pre-producion's ( **this is in fact the IP that should be sent in this case!**) and its corresponding port works OK.

Why do we return an _incorrect_ URL? Should we change it or is it meant to work this way? Since we do not register through production's website, but through FP7-Ofelia...

**Comment by lbergesio** [comment]
Fixed. Using Site.objects.get_current() when possible. Updated site names of production.
