### ISSUE TITLE
Cleanup VM Manager policy code

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#92]
Cleanup unused folder and files:

https://github.com/fp7-ofelia/ocf/tree/ofelia.stable/vt_manager/src/python/vt_manager/controller/policy

Cleanup file:

https://github.com/fp7-ofelia/ocf/blob/ofelia.stable/vt_manager/src/python/vt_manager/controller/policies/ControllerMappings.py
- Delete commented lines
- Write more accurate mapping names. DO NOT delete them, simply add an alias, otherwise it will not be backwards compatible: for instance `vm.project` and `vm.slice` has no real meaning, should be `project` and `slice`. Also `number.vms` should be `project.number_of_vms` or something similar.

**Comment by OscarMoya** [comment]
Done.

Old PolicyManager code deleted and ControllerMappings names improved. 

I'm not sure if there is still any surpluss or if any mapping is missing. Please comment and I will add/remove these.

**Comment by msune** [comment]
Please delete action `something`. Implement a simple `log` action

**Comment by OscarMoya** [comment]
Done.

`logVM` action added to action mappings.When this action is executed, some parameters of a VM (Name |RAM |HD size) are printed.

I also implemented a Logger utility for PolicyEngine called PolicyLogger. This logger records the results of logVM, captures the exceptions raised from terminal rules and shows an "OK!" message when all policies (enabled ones) have been accepted. The output file of this logger is located at `vt_manager/src/python/vt_manager/controller/policies/utils/log/pe.log`

If somethng is still missing, please say so.

**Comment by CarolinaFernandez** [comment]
Permissions of `/opt/ofelia/vt_manager/src/python/vt_manager/controller/policies/utils/log` folder are not OK (VM manager shows internal server error when trying to write to `pe.log`).

For I/O it is required to set user `www-data` or either complete permissions.

**Comment by lbergesio** [comment]
The permissions are now managed by ofver, git ignores them except for the x flag.
