### ISSUE TITLE
ofver scripts to upgrade pypelib

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#95]
default upgrade ofver scripts need a method tu compare pypelib versions and update it if newer version is available.

**Comment by CarolinaFernandez** [comment]
Script modified for upgrade from **default to v0.4** and also from **plain install** in both **expedient** and **vt manager**.

Modified files:

> expedient/bin/versions/0.4/upgrade/default/pre-upgrade-hook
> expedient/bin/versions/default/install/lib/dependencies
> vt_manager/bin/versions/0.4/upgrade/default/pre-upgrade-hook
> vt_manager/bin/versions/default/install/lib/dependencies

If it were needed for further scripts, here is the code:

> ```
> # Installing pyPElib (if not previously installed or version not up to date)
> pypelibUpToDate=`dpkg --get-selections | grep "pypelib" | grep "install"`
> # 1st: install check
> if [[ $pypelibUpToDate != "" ]]; then
>     pypelibCurrentVersion=`sudo dpkg --list pypelib | awk '{for (i=1;i<=NF;i++) if (i==3) { print $i } }' | tail -n 1`
>     sudo /usr/bin/wget https://pypelib.googlecode.com/git/VERSION -O pypelib.version.tmp
>     pypelibLatestVersion=`cat pypelib.version.tmp`
>     rm pypelib.version.tmp
>     if [[ $pypelibCurrentVersion != $pypelibLatestVersion ]]; then
>        $pypelibUpToDate=""
>     fi
> fi
> # 2nd: up-to-date check
> if [[ $pypelibUpToDate == "" ]]; then
>     print "Downloading latest pypelib version..."
>     /usr/bin/wget http://pypelib.googlecode.com/files/pypelib_latest_all.deb || error "Could not download pypelib latest version from http://pypelib.googlecode.com/files/pypelib_latest_all.deb. Do you have connectivity?"
>     print "Installing pypelib_latest_all.deb..."
>     /usr/bin/dpkg -i pypelib_latest_all.deb || error "Could not install pypelib latest version using /usr/bin/dpkg -i pypelib_latest_all.deb"
>     print "Removing temporary files..."
>     rm pypelib_latest_all.deb || "Could not remove pypelib_latest_all.deb"
> fi
> ```

**Comment by CarolinaFernandez** [comment]
**NOTE: realized that I did not commit nor push. Sorry :)**

Also, it would be better to **update** the previous files with the following code:

> ```
> # Checks that Python 2.6 exists or points to current version for pyPElib
> if [[ ! -d /usr/lib/python2.6 ]]; then
>     pyVersion="python"`python -c "import sys; print(sys.version.split(' ')[0])"`
>     i=3
>     while [[ ! -d /usr/lib/$pyVersion && $i -gt 0 ]]; do
>         # Looks for the 'longest' version possible
>         case $i in
>             2) pyVersion="python$(expr "$pyVersion" : 'python\([0-9].[0-9]\).*')" ;;
>             1) pyVersion="python$(expr "$pyVersion" : 'python\([0-9]\).*')" ;;
>         esac
>         i=$((i-1))
>     done
>     if [[ -d /usr/lib/$pyVersion ]]; then
>         ln -s /usr/lib/$pyVersion /usr/lib/python2.6
>     fi
> fi
> # Installing pyPElib (if not previously installed or version not up to date)
> pypelibUpToDate=`dpkg --get-selections | grep "pypelib" | grep "install"`
> # 1st: install check
> if [[ $pypelibUpToDate != "" ]]; then
>     pypelibCurrentVersion=`dpkg --list pypelib | awk '{for (i=1;i<=NF;i++) if (i==3) { print $i } }' | tail -n 1`
>     /usr/bin/wget https://pypelib.googlecode.com/git/VERSION -O pypelib.version.tmp || error "Could not retrieve pypelib version. Do you have connectivity?"
>     pypelibLatestVersion=`cat pypelib.version.tmp`
>     rm pypelib.version.tmp || error "Could not remove pypelib.version.tmp"
>     if [[ $pypelibCurrentVersion != $pypelibLatestVersion ]]; then
>        pypelibUpToDate=""
>     fi 
> fi  
> # 2nd: up-to-date check
> if [[ $pypelibUpToDate == "" ]]; then
>     print "Downloading latest pypelib version..."
>     /usr/bin/wget http://pypelib.googlecode.com/files/pypelib_latest_all.deb || error "Could not download pypelib latest version from http://pypelib.googlecode.com/files/pypelib_latest_all.deb. Do you have connectivity?"
>     print "Installing pypelib_latest_all.deb..."
>     /usr/bin/dpkg -i pypelib_latest_all.deb || error "Could not install pypelib latest version using /usr/bin/dpkg -i pypelib_latest_all.deb"
>     print "Removing temporary files..."
>     rm pypelib_latest_all.deb || "Could not remove pypelib_latest_all.deb"
> fi
> ```

**Comment by lbergesio** [comment]
What about the python version validation and link symbolic creation?

**Comment by lbergesio** [comment]
Added also to : 
expedient/bin/versions/default/upgrade/default/pre-upgrade-hook
vt_manager/bin/versions/default/upgrade/default/pre-upgrade-hook

In order to check always if there is a new version of pypelib

**Comment by lbergesio** [comment]
Line:  $pypelibUpToDate=""
changed to: pypelibUpToDate=""
